<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYfIBaUi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYfIBaUi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYfIBaUi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYfIBaUi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYfIBaUi\App_KernelDevDebugContainer([
    'container.build_hash' => 'YfIBaUi',
    'container.build_id' => '6f98e585',
    'container.build_time' => 1725819438,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYfIBaUi');
