<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'task_index' => [[], ['_controller' => 'App\\Controller\\TaskController::index'], [], [['text', '/']], [], [], []],
    'task_new' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/new']], [], [], []],
    'task_show' => [['id'], ['_controller' => 'App\\Controller\\TaskController::show'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'task_edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\TaskController::index' => [[], ['_controller' => 'App\\Controller\\TaskController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\TaskController::new' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/new']], [], [], []],
    'App\Controller\TaskController::show' => [['id'], ['_controller' => 'App\\Controller\\TaskController::show'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\TaskController::edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\TaskController::delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
];
